### ISSUE TITLE
Login/Signup Feature

### ISSUE THREAD

**Issue by IrhaAli** [chingu-voyages/v46-tier3-team-39#17]
**__Feature Description__**
To allow users to retain and create their quizzes. To be able to access their quizzes repeatedly through this feature.

**__Major User Stories/tasks__**
- [ ] Create a login route
- [ ] Create a signup route
- [ ] Create forgot password route

**__Additional Considerations__**
Include anything else that may be helpful. For example, links to external resources.
